### ISSUE TITLE
Integrate Drupal Cache Clear w/Pantheon Cache Clear

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/drops-8#148]
When a user clicks "clear cache" in the Drupal admin area, it needs to flush Pantheon's edge, as in previous versions. We should explore whether this requires us to replace the `pantheon.module` pattern, or if there's a way to hook to existing module namespace internally (e.g. can we define `system_cache_flush()` and be done with it?)

**Comment by ttrowell** [comment]
@joshkoenig Any forward motion on this Issue?  Thanks!

**Comment by willvedd** [comment]
@joshkoenig +1 this issue. I'd be alright if this was exposed as a hook rather than built as a turn-key solution. Our team is fighting against some inefficiencies in D8, especially when the page cache rebuilds after expiration. We would prefer to increase the max-age of the page cache if we had more intelligent ways of purging varnish.

**Comment by greg-1-anderson** [comment]
This issue was resolved years ago.
