### ISSUE TITLE
Installation Profile Not Approparely Set

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#17]
The installation profile is not properly set resulting in a couple notices on admin pages and this reporting in the system status:

Installation profile	(-)

**Comment by greg-1-anderson** [comment]
In Drupal-8.0-beta9, I had to expand the scope of this issue to also default to the 'standard' installation profile later in the installation process.  Without this change, `Settings::get('install_profile')` returns an empty value, and you run afoul of this code in ConfigInstaller:
```
    // Install profiles can not have config clashes. Configuration that
    // has the same name as a module's configuration will be used instead.
    if ($name != $this->drupalGetProfile()) {
      // Throw an exception if the module being installed contains configuration
      // that already exists. Additionally, can not continue installing more
      // modules because those may depend on the current module being installed.
      $existing_configuration = $this->findPreExistingConfiguration($storage);
      if (!empty($existing_configuration)) {
        throw PreExistingConfigException::create($name, $existing_configuration);
      }
    }
```
Here, and elsewhere in the installation process, Drupal is using `$name != $this->drupalGetProfile()` to mean "if $name is not an installation profile...".  This test is okay during installation, because the only value of $name that **might** be an installation profile is the installation profile the user selected during installation.  If `Settings::get('install_profile')` is not returning the correct value, then the wrong code will run -- in the case of the snippet above, the symptom is a false-positive on the pre-existing configuration test.

Returning 'standard' as the default value for drupalGetProfile() is therefore insufficient, because the test to see if $name is an installation profile is no longer doing a correct comparison.  For example, if the user selects the "minimal" installation profile, then the installation will fail.

**Comment by populist** [comment]
The general problem here is that as part of the installation process the install_profile value is written to the settings.php. However, since we skip the database installation step (where the DB stuff is written to settings.php) I bet the install profile value also gets skipped, hence our problems.

Probably going to define that in settings.php explicitly and look at https://www.drupal.org/node/2451363 for further information here.

**Comment by populist** [comment]
This is now being defined explicitly in settings.php

**Comment by populist** [comment]
As of Drupal 8 Beta 10 the installer is now appropriately setting the value. This however won't work in Git mode (https://github.com/pantheon-systems/drops-8/issues/36), but it will work correctly in SFTP mode and there is another issue for Git mode.
