### ISSUE TITLE
8.2.8 release?

### ISSUE THREAD

**Issue by generalredneck** [pantheon-systems/drops-8#177]
Looks like the automated build may have choked on 8.2.8? I 8.3.1 out... If all else fails, should be able to apply this patch to your site. https://github.com/drupal/drupal/compare/8.2.7...8.2.8.patch

**Comment by generalredneck** [comment]
FYI had to remove the changelog entries... as that seems to hickup.

**Comment by greg-1-anderson** [comment]
The Pantheon dashboard merges commits from the master branch of your site's upstream into your site. It expects people to upgrade sequentially from 8.2.7 to 8.3.0 to 8.3.1.

Since 8.2.8 came out after 8.3.0, there is no way to insert it into this repository in such a way as to make it available to dashboard users.

We could make an 8.2.8 tag on a branch for the benefit of Composer users if there is a need.

**Comment by generalredneck** [comment]
that makes perfect sense and I suspected something of that... in our case, we will be forced to quickly deal with upgrading to 8.3.* where we are having some issues currently, so this would be helpful. we've bout got a patch built out. I'll see if we can get ccjjmartin to do a PR.

**Comment by greg-1-anderson** [comment]
OK, I'll make an 8.2.8 tag for you.

**Comment by generalredneck** [comment]
@greg-1-anderson you are a saint and a scholar

**Comment by greg-1-anderson** [comment]
Hm, my update script accidentally made the PR branch off of the `master` branch instead of the `8.2.8` branch -- but despite that minor glitch, the contents of the PR are correct. You can look at it here:

https://github.com/pantheon-systems/drops-8/pull/178

I'll merge it into the 8.2.x branch and make an 8.2.8 tag as soon as the tests pass.

**Comment by generalredneck** [comment]
You should be able to hit "edit" and change the Base branch if you need to. but I don't know if that matters.

**Comment by greg-1-anderson** [comment]
Yep, that worked nicely. Lots of changes to `vendor`, but that won't matter if you're using [example-drops-8-composer](https://github.com/pantheon-systems/example-drops-8-composer), because it will take the vendor versions from `drupal-core-lock`.

**Comment by greg-1-anderson** [comment]
[8.2.8](https://github.com/pantheon-systems/drops-8/tree/8.2.8) has been tagged.
