### ISSUE TITLE
Enable CORS via .htacess

### ISSUE THREAD

**Issue by enzolutions** [pantheon-systems/drops-8#22]
I'm trying to configure my pantheon dev to accept CORS Request, Drupal 8 don't accept this by default in core until 8.1 according to Dries https://www.drupal.org/node/1869548#comment-9365043

So I did some changes in .htaccess

```
# Intercept OPTIONS calls
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule .* / [R=200,L]
```

and
```
<IfModule mod_headers.c>
  Header always set Access-Control-Allow-Origin "*"
  Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, PATCH, DELETE"
  Header always set Access-Control-Allow-Headers: Authorization
</IfModule>
```

These options works in other environments but in Pantheon the changes are not working.

Any suggestions?

**Comment by joshkoenig** [comment]
.htaccess files have no effect on Pantheon. We run nginx. 

The correct way to handle this is to tell your Drupal application to send the various ```Access-Control``` headers. I do this in my headless Drupal demo:

http://dev-headless-drupal-8.gotpantheon.com/

```
curl -I http://dev-headless-drupal-8.gotpantheon.com/

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
...
```

This is superior to relying on your webserver because it will work across platforms, and because you can control in your application what you would like to allow via cross-origin vs not. For instance, as these use-cases become more widespread I would imagine security minded folks would want to limit what can be cross-origin requests (e.g. nothing in /admin for starters) since allowing cross-origin requests presents a significant XSS attack vector.

**Comment by joshkoenig** [comment]
To be clearer, anything in Drupal can send these headers. You don't need core to do it.

**Comment by enzolutions** [comment]
Hi Josh

Can you shave how you set this header, maybe inside index.php using http://php.net/manual/es/function.header.php ?

**Comment by joshkoenig** [comment]
Sure:

```
<?php
header("Access-Control-Allow-Origin: *");

```

Where you put that in your codebase is up to you. For my case, I just put it in settings.php, but there's probably a more correct place in Drupal 8. In Drupal 7 I'd use:

https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_add_http_header/7

**Comment by enzolutions** [comment]
Nice catchup, I'm sure in the future when Drupal 8 gets more popular Pantheon will provide something in UI,

**Comment by matt-cook** [comment]
Is there a method for adding CORS headers to files served from /sites/default/files on Pantheon? Other than using a proxy PHP script.

**Comment by enzolutions** [comment]
For pantheon I did this article to enable CORS http://enzolutions.com/articles/2015/05/26/how-to-enable-cors-in-drupal-8-in-non-apache-webservers/

**Comment by matt-cook** [comment]
This module https://github.com/previousnext/drupal_cors may also solve this issue for some cases. Unfortunately, as with the patch from @enzolutions it doesn't apply to images/files.
