### ISSUE TITLE
Document How to Add services.yml File

### ISSUE THREAD

**Issue by nikathone** [pantheon-systems/drops-8#26]
How do I add services.yml file under default folder? I am  trying to deploy that file using phpStorm but I am getting permission denied.

**Comment by mikevanwinkle** [comment]
@populist @greg-1-anderson any ideas here? I'm not super familiar with Drupal8 yet.

**Comment by ari-gold** [comment]
@nikathone Not sure if your question is specific to Drupal 8? Is Dev in SFTP mode? See https://pantheon.io/docs/articles/local/configuring-jetbrains-phpstorm-ide-with-pantheon/

**Comment by nikathone** [comment]
@ari-gold I was trying to accomplish this https://www.drupal.org/node/1903374 but I am getting a permission denied every time I try to upload mys custom services.yml file.

**Comment by ari-gold** [comment]
@nikathone Confirmed. I also get a permission denied: https://gist.github.com/ari-gold/bd29d793241ff12a740f

**Comment by populist** [comment]
I can confirm that this happens when in SFTP mode, but does not happen when using .git. The reason for this is the sites/default directory has the permissions of 555 even if you toggle SFTP mode on and off.

My guess on what is happening is that there is some backend logic (maybe in ellis/portal.py) which does permission magic to sites/default based on 'drupal' as a framework but should also do the same magic if the framework is 'drupal8'. Needs more investigating.

**Comment by populist** [comment]
As an update, I now believe that these permissions are being set by Drupal and if we provide appropriate documentation in how to change them (i.e. use SFTP to change permissions) than that will be a reasonable resolution.

**Comment by greg-1-anderson** [comment]
I'm marking this "major" -- even though it is a simple documentation issue, this is something we want to insure to have covered for D8 support.

**Comment by bmackinney** [comment]
@greg-1-anderson this is complete as well: https://github.com/pantheon-systems/documentation/pull/936
