### ISSUE TITLE
Review Default .gitignore file in D8

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#28]
D8 rolls with a .gitignore file - https://www.drupal.org/node/1170538. It should be reviewed to see if it breaks the experience of using D8 on Pantheon.

**Comment by fosterinteractive** [comment]
Just a note - It rolls *without* a .gitignore and has the example.gitignore to copy out to .gitignore so future updates to core won't override your defaults. 

So if you git pull, add 1 file, git add -A, commit  and push you get an error because all drupals tmp files get committed. 

I'm guessing the distro install should include a message telling you you should update this file. The .gitignore itself should be customized to pantheon's requirements.

**Comment by populist** [comment]
Thanks for clarifying! Just want to make sure that if folks rock a .gitignore it wont cause no serious troubles for Pantheon operations.

**Comment by populist** [comment]
I did a review of the current example.gitignore (http://cgit.drupalcode.org/drupal/tree/example.gitignore) and outside of the restriction against sites/*/settings*.php we should be fine. My assumption is users will just handle that as they think appropriate, although if it becomes a problem we can change it in DROPS-8.
