### ISSUE TITLE
Let's Remove the Git History from Drupal Core in DROPS-8

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#50]
Why not remove the Drupal core history from DROPS-8? Very few developers, if any, actually access this history on their local site (versus on Drupal.org) and it slows down all sorts of operations since there is a lot of Drupal history.

**Comment by greg-1-anderson** [comment]
First open question here is whether we should just rewrite history on drops-8 (breaking existing Pantheon D8 sites), or if we want to create a new repository with squashed history.

An alternative would be to just continue using drops-8, but only squash core history on future updates.

**Comment by nstielau** [comment]
I think we can truncate history on DROPS-8 and still have those sites keep
working on Pantheon, and give users some git commands to sort out their
local environments.  Notice I am not offering the details of how to do
this, but I think it is possible, and could be the best way forward.

Avoiding other repos will help keep things clear in the future.

Also, D8 is beta on Pantheon and folks expect some potholes.  There are
huge performance benefits to doing this.

On Thu, Aug 13, 2015 at 10:29 AM, Greg Anderson <notifications@github.com>
wrote:

> First open question here is whether we should just rewrite history on
> drops-8 (breaking existing Pantheon D8 sites), or if we want to create a
> new repository with squashed history.
>
> An alternative would be to just continue using drops-8, but only squash
> core history on future updates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/drops-8/issues/50#issuecomment-130771249>
> .
>



-- 
Nick Stielau | p 415-515-2120
Director of Engineering | Pantheon

**Comment by greg-1-anderson** [comment]
Yeah, "break" is too strong a word. There are indeed git commands that will fix any such site; we could publish a recipe.

**Comment by greg-1-anderson** [comment]
The next question is, WHEN should we do this?  I'd like to get 8.0.0-beta14 deployed soon; should we do this release with or without the squashed history?

My thought is to just write a simple script that walks through all of the tags, checks them out one at a time, and makes a new commit (in a new empty repository) for each in turn.  Or just do the same manually, since there are only a few tags.  Or we could just start with 8.0.0-beta14 with no old tags.  Since there's no upgrade path from older versions of Drupal 8 anyway, the value of the old tags is minimal.

**Comment by tormi** [comment]
Blocks #51 .

**Comment by greg-1-anderson** [comment]
Drupal 8.0.0-beta15 was not released today, as it is blocked on a few bugs that are required for the upgrade path to work.  We can expect the Drupal 8 release to be a little less regular from here on out, I expect.

So, we are going to move forward here and deploy the new reduced-history repository on 8.0.0-beta14.  Note that beta14 has already been deployed on the platform on the existing repository.  I have prepared a new repository for Drops 8 containing only one commit for beta12, one commit for beta14, and one commit for each of the Pantheon changes required for Drops-8.

The reduced repository preview is available at:

https://github.com/greg-1-anderson/drops-8

Here is a summary of what is in the new repository:
```
0c7f404 2015-08-26 Pantheon Automation Update to Drupal 8.0.0-beta14. For more information, see: https://www.drupal.org/node/2544542
2ec338a 2015-08-26 Greg Anderson Fixes #58. Include install.core.inc in addtion to install.inc, because that is what install.php does.
ec97eb4 2015-08-26 Greg Anderson Fixes #17:  Pre-select the 'standard' installation profile.
f7790fd 2015-08-26 Greg Anderson Fixes #59: Include services.yml from settings.php.
478e8ea 2015-08-26 Greg Anderson Fix comparison error in settings.php.
80270ec 2015-08-17 Greg Anderson Pantheon settings.php files. pantheon-systems/drops-8#55.
c8c01bb 2015-08-17 Greg Anderson Placeholder config directory.
69f2855 2015-08-17 Greg Anderson Lock Drupal Core to prevent drush pm-update on Pantheon code base.
ee0385f 2015-08-17 Greg Anderson Pantheon-specific .gitignore file.
9921556 2015-08-17 Pantheon Automation Drupal 8.0.0 beta 12. More info: https://www.drupal.org/node/2514176
```
Note that the new reduced repository contains *no core hacks*.  The new drops-8 is just the standard Drupal 8.0.0-beta14, with custom `settings.php` (that the end user can modify) and `settings.pantheon.php` files.  This will make future maintenance easier for Pantheon, and will also greatly improve the experience for anyone who wants to use Composer to manage their Pantheon Drupal 8 site, as the standard split core repository can be used.

This repository includes all of the currently-open PRs labeled "major", although these have been inserted before the commit for Drupal 8.0.0-beta14, even though these occur after the beta14 release in the current repository. This was done to conform to our usual policy of always leaving the "Pantheon Automation" commit "on top" of the commit history. Since the entire repository is being recreated, this bit of history rewriting should not have much impact on anyone.

It is expected that most people will not try to fix their site for the new repository, but will just delete their existing site and create a new one with the new repository.  This is the easiest route, and will provide a smooth upgrade path to Drupal 8.0.0-beta15 once it is available.

For those who do wish to fix an existing site, they may either proceed as above, and then copy their database and configuration on top of their new site, or, alternately, we can provide the git commands necessary to repair a site after the change-over.  The process is, roughly:

1. Rename your current `master` branch to something else.
2. Fetch the new reduced `master` branch from drops 8 (git remote add, git fetch).
3. Cherry-pick the changes made on the existing site onto the new `master` branch.
4. Force-push master up to your Pantheon site.

As previously mentioned, the overall developer experience with the new repository should go way up

**Comment by tormi** [comment]
:+1:

**Comment by greg-1-anderson** [comment]
This is going out shortly. There will be a bulk email sent to everyone who has spun up a Drupal 8 site going out at noon Pacific today, pointing folks at this issue for more info.

**Comment by nstielau** [comment]
Go Greg!

On Thu, Aug 27, 2015 at 9:52 AM, Greg Anderson <notifications@github.com>
wrote:

> This is going out shortly. There will be a bulk email sent to everyone who
> has spun up a Drupal 8 site going out at noon Pacific today, pointing folks
> at this issue for more info.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/drops-8/issues/50#issuecomment-135491109>
> .
>



-- 
Nick Stielau | p 415-515-2120
Director of Engineering | Pantheon

**Comment by heddn** [comment]
Thanks. This will help a lot with the amount of data pulled. No need for all that lengthy drupal history in the repo.

**Comment by bensheldon** [comment]
Is there a playbook for generating squashed "releases"? For example, will Pantheon-specific customizations be squashed into Drupal-core commits, or will we keep those separate?

Unless I'm wrong, by squashing Pantheon will need to do a bit more work to produce these releases and rely on raw diffs to ensure our releases are synonymous with complete Drupal history. 

I'm in support of the change, but by altering history we'll have to track a few more things manually since git won't have the granular commit data.

**Comment by greg-1-anderson** [comment]
The scripts for updating Drops are in the project [pantheon-systems/downstream-updater](https://github.com/pantheon-systems/downstream-updater). These are still in development, but I the script that updates with a single squashed commit should be ready in time to use with Drupal 8.0.0-beta15.

The squashed repository has been pushed out; you can [look at the commits](https://github.com/pantheon-systems/drops-8/commits/master) to see how it came out.  (Also, see the [preview in the comment above](https://github.com/pantheon-systems/drops-8/issues/50#issuecomment-135203319).)  As you can see, each Pantheon-specific customization is kept as a separate commit, so we have a history of what changed, and when.  For the history of changes for Drupal, folks who are interested in that can check out the repository from drupal.org.

It is true that we will need to carefully track all of our upstream updates.  This shouldn't be too hard, because:

- We can do the update with a script, ensuring that it happens consistently every time.
- We put the Drupal version number in the commit comment, so it is readily visible in the git log.
- We tag each Drupal update commit with the version number, so that it is easy to find older releases.
- We are now running Drupal 8 unmodified on Pantheon, save for changes introduced via settings.php, so direct comparisons with the equivalent Drupal release will be pretty easy to do, should anyone have any doubt, or need to confirm the files being used for any reason.

**Comment by greg-1-anderson** [comment]
## Instructions for Updating Existing Sites

### Easy and recommended option: delete your site and create a new one

For sites that do not contain any useful data, the easiest way to go is to just delete your existing site, and create a new one from scratch. If you want to, you could copy your existing site's configuration .yml files and database over to the new site before deleting the old site.

### Lazy option: do nothing

If you do not do anything at all, you will still be able to update your Drupal 8 sites from the dashboard.  You will need to check the "resolve conflicts" checkbox for this to work.  All of the new commits will be added on top of the existing commits; everything should still work, but your repository will remain large.  If you changed anything in settings.php, these will be erased; however, Pantheon should not add anything to settings.php in future releases [1], so once you put your customizations back in, you probably won't need to do this again.

[1] *Not guaranteed until Drupal 8 is officially supported.*

### Advanced option: rebuild your site's repository

Run the following commands:
```
git remote add drops-8 git@github.com:pantheon-systems/drops-8.git
git checkout -b existing
git fetch drops-8
git branch -d master
checkout -b master drops-8/master
```
At this point, you should run `git cherry-pick` as necessary to pick up any of your existing commits that you might want to keep.  Resolve conflicts as necessary, then continue:
```
git push origin master --force
git branch -D existing
```
